# -*- coding: utf-8 -*-
"""ANALISIS_02_ PEREZ_MARIANA

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1g2RfzBJSab3a5VrSVXBosv57beiqx2KU
"""

import csv
import pandas as pd

#importar csv y pandas que nos ayudaran a poder leer los archivos csv y pandas para manejar la base de datos

synergy_df = pd.read_csv("synergy_logistics_database.csv")

#leer el csv correspondiente a este trabajo y asignarlo a una variable

synergy_df

#mostrar la base de datos, de esta manera podemos darnos una idea de los datos que se manejan y poder crear buenas preguntas para el análisis

synergy_df.dtypes

#corroborar los tipos de datos existentes

"""Opción 1) Rutas de importación y exportación. Synergy logistics está considerando la posibilidad de enfocar sus esfuerzos en las 10 rutas más demandadas. Acorde a los flujos de importación y exportación, ¿cuáles son esas 10 rutas?"""

exportacion = synergy_df[synergy_df["direction"] == "Exports"].groupby(["origin", "destination", "transport_mode" ])
#crear una variable donde se encuentren solamente los datos de exportación
#agruparlos por origen, destino y medio de transporte

top_10_exportacion = exportacion.sum("total_value")["total_value"].sort_values(ascending=False).head(10)
#Solo mostrar el top 10 de mayor a menor

top_10_exportacion

importacion =  synergy_df[synergy_df["direction"] == "Imports"].groupby(["origin", "destination", "transport_mode" ])
top_10_importacion = importacion.sum("total_value")["total_value"].sort_values(ascending=False).head(10)

#crear una variable donde se encuentren solamente los datos de importación
#agruparlos por origen, destino y medio de transporte y mostrar el top 10 de mayor a menor

top_10_importacion

exp = top_10_exportacion.to_frame().reset_index()
imp = top_10_importacion.to_frame().reset_index()

#Convertir las dos series recientemente creadas a dataframes para poder sumar el total value

estrategia_1 = (exp['total_value'].sum())+ (imp['total_value'].sum())
estrategia_1
#El total generado si se opta por la estrategia 1

"""Opción 2) Medio de transporte utilizado. ¿Cuáles son los 3 medios de transporte más importantes para Synergy logistics considerando el valor de las importaciones y exportaciones? ¿Cuál es medio de transporte que podrían reducir? 

"""

transporte_imp = synergy_df[synergy_df["direction"] == "Imports"].groupby("transport_mode").sum("total_value")["total_value"].sort_values(ascending=False).head(3)
transporte_imp
#crear una variable donde se agrupe el dataset por medio de transporte y solamente de Importaciones
#mostrar los 3 medios de transporte que mas generan ingresos

transporte_exp = synergy_df[synergy_df["direction"] == "Exports"].groupby("transport_mode").sum("total_value")["total_value"].sort_values(ascending=False).head(3)
transporte_exp
#crear una variable donde se agrupe el dataset por medio de transporte y solamente de Exportaciones
#mostrar los 3 medios de transporte que mas generan ingresos

transp_exp = transporte_exp.to_frame().reset_index()
transp_imp = transporte_imp.to_frame().reset_index()

estrategia_2 = transp_exp['total_value'].sum() +  transp_imp['total_value'].sum()
estrategia_2

transporte_menos_usado_exp = synergy_df[synergy_df["direction"] == "Exports"].groupby("transport_mode").sum("total_value")["total_value"].sort_values(ascending=True).head(1)
#mostrar el medio de transporte que menos genera ingresos de exportaciones

transporte_menos_usado_exp

transporte_menos_usado_imp = synergy_df[synergy_df["direction"] == "Imports"].groupby("transport_mode").sum("total_value")["total_value"].sort_values(ascending=True).head(1)
#mostrar el medio de transporte que menos genera ingresos de exportaciones

transporte_menos_usado_imp

"""Opción 3) Valor total de importaciones y exportaciones. Si Synergy Logistics quisiera enfocarse en los países que le generan el 80% del valor de las exportaciones e importaciones ¿en qué grupo de países debería enfocar sus esfuerzos?"""

synergy_df['cumsum'] = synergy_df['total_value'].cumsum()
#agregar una columna donde por cada fila, se ira acumulando la suma de total value

acumulado = synergy_df.groupby(["origin", "direction"]).sum("total_value")["total_value"].sort_values(ascending=False)
#crear una variable donde se muestren los datos de los paises de origen y la dirección (exportacion o importación)
#se suma los importes de cada pais y se ordena de mayor a menor

from pandas.core.frame import DataFrame
acu_df = DataFrame(acumulado)
#convertir esta variable en dataframe

acu_df['cumsum'] = acu_df['total_value'].cumsum()
# en este dataframa, agregarle una columna donde por cada fila se acumule la suma del total value de cada pais

total = acu_df['total_value'].sum()
# sumar todo el total value para obtener cuales son los ingresos totales

total

acu_df['porcentaje_acumulado'] = (acu_df.total_value.cumsum() / (total)) * 100
#crear una nueva columna donde se represente el porcentaje acumulado de los ingresos, de esta manera podemos
#determinar que paises son los que abarcan el 80% de los ingresos

acu_df